users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('users-list/', views.UsersListView.as_view(), name='users_list'),
    path('user-update/<str:pk>/', views.UserUpdateView.as_view(), name='user_update'),
    path('user-detail/<str:pk>/', views.UserDetailView.as_view(), name='user_detail'),
    path('register/', views.UserCreateView.as_view(), name='user_register')
]

workout_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from debug_toolbar.toolbar import debug_toolbar_urls

from .views import IndexView
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('users/', include('users.urls', namespace='users')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('workouts/', include('workouts.urls.urls', namespace='workouts')),
]

if settings.DEBUG:
    urlpatterns += debug_toolbar_urls()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    {% load static %}
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>

<div class="container-fluid p-2 bg-dark">
    <nav class="nav">
        <a class="nav-link active" href="{% url 'index' %}">To main page</a>
        <a class="nav-link active" href="{% url 'workouts:exercises_list' %}">Exercises list</a>
        <a class="nav-link active" href="{% url 'workouts:exercise_categories_list' %}">Exercise categories</a>
        <a class="nav-link active" href="{% url 'workouts:training_plan_list' %}">Training plans</a>
        {#  Next elements should be added after element with a ms-auto class.  #}
        <a class="nav-link active ms-auto">Hello, {{ user.username|default:"Guest" }}!</a>
        <a class="nav-link active" href="{% url 'admin:index' %}">To admin panel</a>
        {% if user.is_authenticated %}
            <form method="post" action="{% url 'logout' %}">
                {% csrf_token %}
                <button class='form-control btn btn-outline-primary' type="submit">Log out</button>
            </form>
        {% else %}
            <a class="nav-link active" href="{% url 'login' %}">Log in</a>
        {% endif %}
    </nav>
</div>


{% block content %}

{% endblock %}

{% block script %}

{% endblock %}

</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap5 %}

{% block title %}
    Index
{% endblock %}

<body>

{% block content %}
    <ul>

        <li>
            <a href="{% url 'users:user_register' %}">Registration</a>
        </li>
        <li>
            <a href="{% url 'users:users_list' %}">Users</a>
        </li>
    </ul>

{% endblock %}


{% block script %}

{% endblock %}

</body>